<?php
require_once '../db.php';

$input = file_get_contents('php://input');
$data = json_decode($input, true);

$distributorId = isset($data['distributor_id']) ? (int)$data['distributor_id'] : 0;
$agentId = isset($data['agent_id']) ? (int)$data['agent_id'] : 0;

if (empty($distributorId) && empty($agentId)) {
    http_response_code(400);
    echo json_encode(["status" => "error", "message" => "Required parameter (distributor_id or agent_id) is missing."]);
    exit();
}

try {
    // 1. Base query for MLM orders under this user
    if (!empty($agentId)) {
        $orderQuery = "
            SELECT o.id, o.buyer_id, u.name as buyer_name, o.school_name, o.school_address, o.contact_person, o.mobile_number,
                   o.total_amount, o.payment_status, o.delivery_status, o.order_type, o.created_at,
                   oi.quantity, k.level as kit_level
            FROM kit_orders o
            JOIN users u ON o.buyer_id = u.id
            JOIN kit_order_items oi ON o.id = oi.order_id
            JOIN kits k ON oi.kit_id = k.id
            WHERE (o.agent_id = ? OR o.buyer_id = ?) AND o.order_type = 'MLM'
        ";
        $params = [$agentId, $agentId];
    } else {
        $orderQuery = "
            SELECT o.id, o.buyer_id, u.name as buyer_name, o.school_name, o.school_address, o.contact_person, o.mobile_number,
                   o.total_amount, o.payment_status, o.delivery_status, o.order_type, o.created_at,
                   oi.quantity, k.level as kit_level
            FROM kit_orders o
            JOIN users u ON o.buyer_id = u.id
            JOIN kit_order_items oi ON o.id = oi.order_id
            JOIN kits k ON oi.kit_id = k.id
            WHERE o.distributor_id = ? AND o.order_type = 'MLM'
        ";
        $params = [$distributorId];
    }
    
    $orderQuery .= " ORDER BY o.id DESC";

    $stmt = $conn->prepare($orderQuery);
    $stmt->execute($params);
    $orders = $stmt->fetchAll(PDO::FETCH_ASSOC);

    // 2. Aggregate metrics for MLM sales
    $totalSales = 0.00;
    $totalKits = 0;
    $recipientId = !empty($agentId) ? $agentId : $distributorId;

    $orderIds = array_map(function($o) { return $o['id']; }, $orders);
    $orderCommissions = [];
    if (!empty($orderIds)) {
        $inQuery = implode(',', array_fill(0, count($orderIds), '?'));
        $stmtC = $conn->prepare("
            SELECT order_id, COALESCE(SUM(amount), 0.00) as amt 
            FROM commissions 
            WHERE recipient_id = ? AND order_id IN ($inQuery)
            GROUP BY order_id
        ");
        $stmtC->execute(array_merge([$recipientId], $orderIds));
        while ($cRow = $stmtC->fetch(PDO::FETCH_ASSOC)) {
            $orderCommissions[(int)$cRow['order_id']] = (float)$cRow['amt'];
        }
    }
    
    foreach ($orders as &$o) {
        $totalSales += (float)$o['total_amount'];
        $totalKits += (int)$o['quantity'];
        $o['commission_earned'] = isset($orderCommissions[(int)$o['id']]) ? $orderCommissions[(int)$o['id']] : 0.00;
    }
    unset($o);

    // Get total commissions earned
    $recipientId = !empty($agentId) ? $agentId : $distributorId;
    $stmtComm = $conn->prepare("
        SELECT COALESCE(SUM(amount), 0.00) as total 
        FROM commissions 
        WHERE recipient_id = ?
    ");
    $stmtComm->execute([$recipientId]);
    $totalCommission = (float)$stmtComm->fetch()['total'];

    // Get active/total agents count
    $agentsList = [];
    $currentId = $recipientId;
    $agentCount = 0;
    $activeCount = 0;
    while ($agentCount < 7) {
        $stmtCheck = $conn->prepare("
            SELECT u.id, u.name, u.status 
            FROM user_relations ur
            JOIN users u ON ur.child_id = u.id
            WHERE ur.parent_id = ? AND u.role = 'Agent'
        ");
        $stmtCheck->execute([$currentId]);
        $relation = $stmtCheck->fetch();
        if (!$relation) {
            break;
        }
        $agentCount++;
        if ($relation['status'] === 'Active') {
            $activeCount++;
        }
        $agentsList[] = $relation;
        $currentId = (int)$relation['id'];
    }

    // Get commissions generated by this agent for the distributor
    $agentGeneratedCommission = 0.00;
    if (!empty($agentId) && !empty($distributorId)) {
        $stmtGen = $conn->prepare("
            SELECT COALESCE(SUM(c.amount), 0.00) as total 
            FROM commissions c
            JOIN kit_orders o ON c.order_id = o.id
            WHERE c.recipient_id = ? AND (o.agent_id = ? OR o.buyer_id = ?)
        ");
        $stmtGen->execute([$distributorId, $agentId, $agentId]);
        $agentGeneratedCommission = (float)$stmtGen->fetch()['total'];
    }

    echo json_encode([
        "status" => "success",
        "total_sales" => $totalSales,
        "total_kits" => $totalKits,
        "total_commission" => $totalCommission,
        "agent_generated_commission" => $agentGeneratedCommission,
        "total_agents" => $agentCount,
        "active_agents" => $activeCount,
        "orders" => $orders
    ]);

} catch (Exception $e) {
    echo json_encode(["status" => "error", "message" => $e->getMessage()]);
}
?>
